export default {
  聊天机器人: [
    {
      title: "ATalk智能AI",
      desc: "高颜值AI网站，同时集成ChatgGPT,Midjourney两大主流AI引擎，chatgpt响应速度极快，支持数据分析，Echarts图表展示，mijdourney调用官方接口，实时展示绘图效果",
      href: "https://tool.aiofchina.com/sites/697.html",
      url: "https://www.weijiwangluo.com/talk",
    },
    {
      title: "ChatGPT",
      desc: "ChatGPT 是一种以对话方式进行交互的模型。",
      href: "https://tool.aiofchina.com/sites/16.html",
      url: "https://openai.com/blog/chatgpt/",
    },
    {
      title: "ChatGPTBot",
      desc: "由 ChatGPT 提供支持的 Twitter机器人。 只需 @ 提示即可开始对话。",
      href: "https://tool.aiofchina.com/sites/28.html",
      url: "https://twitter.com/ChatGPTBot/",
    },
    {
      title: "Poe",
      desc: "Quora 为您的移动设备量身定制的用户友好型 GPT-3 界面。",
      href: "https://tool.aiofchina.com/sites/17.html",
      url: "https://poe.quora.com",
    },
    {
      title: "deepseek",
      desc: "深度求索人工智能基础技术研究有限公司(简称“深度求索”或“DeepSeek”)，成立于2023年，是一家专注于实现AGI的中国公司。",
      href: "https://tool.aiofchina.com/sites/768.html",
      url: "https://www.deepseek.com/",
    },
    {
      title: "kimi",
      desc: "Kimi是由月之暗面科技有限公司开发的人工智能助手，擅长中英文对话。它可以处理各种信息，包括文本、PDF、Word文档、PPT幻灯片和Excel电子表格等格式的文件，并能通过互联网搜索获取信息。Kimi致力于以安全、准确的方式帮助用户解决问题，提供有帮助和友好的回复。它不仅能够进行日常对话，还能在学术、生活、工作等多个领域为用户提供支持和建议。",
      href: "https://tool.aiofchina.com/sites/766.html",
      url: "https://kimi.moonshot.cn/",
    },
    {
      title: "智渡AI留学-英文文书简历推荐信",
      desc: "智渡AI留学平台提供了英文文书、推荐信、简历、套磁信生成服务，并且可实现AI率检测和降AI率的能力。 此外，智渡AI留学还引入了智能选校功能，只需提供本科学校和成绩，便可以体验AI智能选校。",
      href: "https://tool.aiofchina.com/sites/762.html",
      url: "https://www.wisdomb.cn",
    },
    {
      title: "Gemini",
      desc: "轻松对话，让 Google AI 帮你写作、规划、学习或处理其他事务",
      href: "https://tool.aiofchina.com/sites/747.html",
      url: "https://gemini.google.com",
    },
    {
      title: "腾讯混元大模型",
      desc: "由腾讯研发的大语言模型，具备强大的中文创作能力， 复杂语境下的逻辑推理能力，以及可靠的任务执行能力",
      href: "https://tool.aiofchina.com/sites/729.html",
      url: "https://hunyuan.tencent.com",
    },
    {
      title: "中科院紫东太初多模态大模型",
      desc: "中科院紫东太初多模态大模型",
      href: "https://tool.aiofchina.com/sites/721.html",
      url: "https://gitee.com/zidongtaichu/multi-modal-models",
    },
    {
      title: "百川大模型",
      desc: "汇聚世界知识，创作妙笔生花",
      href: "https://tool.aiofchina.com/sites/719.html",
      url: "https://www.baichuan-ai.com/home",
    },
    {
      title: "清华大学chatglm",
      desc: "旨在推动大模型的科学研究，面向高校学术交流与行业合作的试用申请",
      href: "https://tool.aiofchina.com/sites/701.html",
      url: "https://chatglm.cn",
    },
    {
      title: "Chatdoc",
      desc: "ChatDOC是一款基于ChatGPT的文件阅读助手，可以  快速从文档中提取、定位、汇总信息。",
      href: "https://tool.aiofchina.com/sites/663.html",
      url: "https://chatdoc.com",
    },
    {
      title: "MiniGPT-4",
      desc: "MiniGPT-4:通过高级大型语言模型增强视觉语言理解。",
      href: "https://tool.aiofchina.com/sites/660.html",
      url: "https://github.com/Vision-CAIR/MiniGPT-4",
    },
    {
      title: "Claude",
      desc: "下一代 AI 助手，无论规模大小",
      href: "https://tool.aiofchina.com/sites/657.html",
      url: "https://www.anthropic.com/product",
    },
    {
      title: "Bard",
      desc: "谷歌聊天机器人Bard",
      href: "https://tool.aiofchina.com/sites/649.html",
      url: "https://bard.google.com",
    },
    {
      title: "Agent GPT",
      desc: "AgentGPT允许您配置和部署自治AI代理。命名自己的自定义AI并使其实现可想象的任何目标,它将通过考虑要执行的任务,执行任务并从结果中学习来尝试实现目标",
      href: "https://tool.aiofchina.com/sites/647.html",
      url: "https://agentgpt.reworkd.ai/zh",
    },
    {
      title: "Auto-GPT",
      desc: "Auto-GPT是一个实验性的开源应用程序,展示了GPT-4语言模型的功能。. 在GPT-4的推动下,该程序将LLM的“思想”联系在一起,以自主实现您设定的目标。. 作为GPT-4完全自主运行的第一个示例之一,Auto-GPT突破了AI可能性的界限。",
      href: "https://tool.aiofchina.com/sites/645.html",
      url: "https://github.com/Significant-Gravitas/Auto-GPT",
    },
    {
      title: "通义千问",
      desc: "阿里聊天机器人",
      href: "https://tool.aiofchina.com/sites/637.html",
      url: "https://tongyi.aliyun.com",
    },
    {
      title: "aski.ai",
      desc: "AI问答与创作服务，支持AI聊天、AI写作、AI绘画、AI翻译，可辅助创作、编写文案、优化作品，支持基于Stable Diffusion的绘画，Mindjourney风格绘画.",
      href: "https://tool.aiofchina.com/sites/615.html",
      url: "https://aski.ai",
    },
    {
      title: "文心一言",
      desc: "百度全新一代知识增强大语言模型，文心大模型家族的新成员，能够与人对话互动，回答问题，协助创作，高效便捷地帮助人们获取信息、知识和灵感。",
      href: "https://tool.aiofchina.com/sites/571.html",
      url: "https://yiyan.baidu.com/welcome",
    },
    {
      title: "Hotoke ai",
      desc: "机械佛会回答您的问题",
      href: "https://tool.aiofchina.com/sites/564.html",
      url: "https://hotoke.ai",
    },
    {
      title: "OneReach",
      desc: "内置对话式 AI 的无代码/低代码流程自动化平台。",
      href: "https://tool.aiofchina.com/sites/37.html",
      url: "https://onereach.ai",
    },
    {
      title: "[完全免费]BibleGPT",
      desc: "与圣经交谈。 提出问题或记住特定的经文",
      href: "https://tool.aiofchina.com/sites/36.html",
      url: "https://biblegpt.org/",
    },
    {
      title: "Kili",
      desc: "无需使用代码即可构建您自己的个性化 AI 助手。",
      href: "https://tool.aiofchina.com/sites/35.html",
      url: "https://www.kili.so",
    },
    {
      title: "Chatbase",
      desc: "只需上传一个 pdf 并获得一个基于 GPT 的聊天机器人，它可以回答关于它的任何问题。 然后通过我们的 API 将其添加到您的网站。",
      href: "https://tool.aiofchina.com/sites/34.html",
      url: "https://www.chatbase.co/",
    },
    {
      title: "Humata",
      desc: "Humata 就像您的文件的 ChatGPT。 立即提出有关任何文件的问题并获得答案。",
      href: "https://tool.aiofchina.com/sites/32.html",
      url: "https://www.humata.ai/",
    },
    {
      title: "Character.AI",
      desc: "创建您自己的 AI，随时可以帮助您处理任何事情。",
      href: "https://tool.aiofchina.com/sites/30.html",
      url: "https://beta.character.ai/",
    },
    {
      title: "Chatsonic",
      desc: "创建 SEO 优化和无抄袭的内容 将您的博客、广告、电子邮件和网站速度提高 10 倍",
      href: "https://tool.aiofchina.com/sites/29.html",
      url: "https://writesonic.com/",
    },
    {
      title: "ChatBotKit",
      desc: "构建您自己的聊天机器人，可以用自然语言与用户交流。",
      href: "https://tool.aiofchina.com/sites/22.html",
      url: "https://chatbotkit.com",
    },
    {
      title: "Jasper Chat",
      desc: "与非常人性化AI 进行自然对话。",
      href: "https://tool.aiofchina.com/sites/21.html",
      url: "https://www.jasper.ai",
    },
    {
      title: "[开源]GPT Discord Bot",
      desc: "Python Discord 机器人与 text-davinci-003 API 进行对话。",
      href: "https://tool.aiofchina.com/sites/19.html",
      url: "https://github.com/openai/gpt-discord-botPython",
    },
    {
      title: "XP1",
      desc: "XP1 是一个基于 GPT 的助手，可以访问您的浏览器选项卡内容。",
      href: "https://tool.aiofchina.com/sites/18.html",
      url: "https://xp1.dust.tt",
    },
    {
      title: "GPT4FREE",
      desc: "搭建一个免费的GPT4",
      href: "https://tool.aiofchina.com/sites/682.html",
      url: "https://github.com/xtekky/gpt4free",
    },
  ],
  图像生成: [
    {
      title: "AI绘画交流论坛",
      desc: "本论坛专为AI绘画爱好者交流分享使用，晒出你最得意的作品",
      href: "https://tool.aiofchina.com/sites/725.html",
      url: "https://pic.aiofchina.com",
    },
    {
      title: "Midjourney",
      desc: "使用用户提示创建视觉效果。",
      href: "https://tool.aiofchina.com/sites/42.html",
      url: "https://www.midjourney.com",
    },
    {
      title: "DALL·E 2",
      desc: "DALL·E 2 是一个人工智能系统，可以根据描述创建图像。",
      href: "https://tool.aiofchina.com/sites/43.html",
      url: "https://openai.com/dall-e-2/",
    },
    {
      title: "Stable diffusion",
      desc: "开源的AI画图软件",
      href: "https://tool.aiofchina.com/sites/573.html",
      url: "https://github.com/CompVis/stable-diffusion",
    },
    {
      title: "DALL-E-3",
      desc: "openai的dall-e-3画画功能",
      href: "https://tool.aiofchina.com/sites/734.html",
      url: "https://openai.com/dall-e-3",
    },
    {
      title: "ideogram",
      desc: "可以精确展示文字的AI绘画",
      href: "https://tool.aiofchina.com/sites/717.html",
      url: "https://ideogram.ai/login",
    },
    {
      title: "civitai",
      desc: "Civitai是稳定扩散 AI 艺术模型的平台。浏览来自越来越多的创作者的数千个模型集合。",
      href: "https://tool.aiofchina.com/sites/714.html",
      url: "https://civitai.com",
    },
    {
      title: "stability.ai",
      desc: "人民的AI",
      href: "https://tool.aiofchina.com/sites/703.html",
      url: "https://stability.ai",
    },
    {
      title: "ANIMATED DRAWINGS",
      desc: "通过动画人物来移动，使孩子们的绘画栩栩如生!",
      href: "https://tool.aiofchina.com/sites/686.html",
      url: "https://sketch.metademolab.com/",
    },
    {
      title: "NMKD Stable Diffusion GUI",
      desc: "Stable diffuision整合图形界面（AMD可用），无需部署，上手即用",
      href: "https://tool.aiofchina.com/sites/665.html",
      url: "https://nmkd.itch.io/t2i-gui",
    },
    {
      title: "无界AI",
      desc: "中文咒语作画",
      href: "https://tool.aiofchina.com/sites/622.html",
      url: "https://www.wujieai.com",
    },
    {
      title: "爱作画",
      desc: "在爱作画AIGC开放平台，您可以使用到与开源社区同步的最新开源AI模型，也可以自己上传AI模型或使用其他创作者分享的AI模型进行创作",
      href: "https://tool.aiofchina.com/sites/620.html",
      url: "https://www.aizuohua.com/#/aicz",
    },
    {
      title: "造梦日记",
      desc: "只需一句话，让你的文字变成画作",
      href: "https://tool.aiofchina.com/sites/618.html",
      url: "https://printidea.art",
    },
    {
      title: "aiseo",
      desc: "AISEO艺术是一款AI小助手，帮你把想法变成艺术。您可以在几分钟内生成高质量的艺术作品。此外，AISEO也可以帮助您低成本创建创意图稿。",
      href: "https://tool.aiofchina.com/sites/605.html",
      url: "https://art.aiseo.ai",
    },
    {
      title: "Luma AI",
      desc: "Luma 提供了一种使用通过手机生成逼真 3D 效果的方法。借助 Luma AI 的神经渲染技术，用户可以仅使用几张图像来创建、着色和渲染逼真的 3D 产品模型。无论您走到哪里，捕捉商品、物品、风景和场景都会变得很简单，不需要昂贵的专业设备，利用手机相机就可以创建不可思议的产品影片。",
      href: "https://tool.aiofchina.com/sites/589.html",
      url: "https://lumalabs.ai",
    },
    {
      title: "Kaiber",
      desc: "Kaiber 可以根据输入的照片、文字或视频片段等各种信息，依据AI和机器学习（ML）算法用来自动生成创意视频。在其尖端的人工智能生成引擎下，将用户脑海中的概念变成现实，让想象力得到真正的释放。",
      href: "https://tool.aiofchina.com/sites/583.html",
      url: "https://www.kaiber.ai",
    },
    {
      title: "Img2Prompt",
      desc: "Img2Prompt 利用 Replicate 平台，通过AI技术从所上传的照片中提取相关的文本提示。该应用程序使用复杂的计算机视觉算法来分析图片，并产生一段文本总结图片的内容。用户使用 Img2Prompt 能够迅速创建高水准的文本提示，精确解释他们正在处理的照片，降低和简化了制作 AIGC 图片内容的难度。",
      href: "https://tool.aiofchina.com/sites/581.html",
      url: "https://replicate.com/methexis-inc/img2prompt",
    },
    {
      title: "Latent Labs",
      desc: "Latent Labs 能将文本内容转换为360°的全景图像，为AI艺术带来了一种新的体验。Latent Labs 专注于人工智能(AI)和自然语言处理(NLP)的交叉研究，因此你可以探索一个新的创意维度，该团队目前致力于修复接缝和提高图像质量，当前仅是alpha版本，可免费使用。",
      href: "https://tool.aiofchina.com/sites/579.html",
      url: "https://www.latentlabs.art",
    },
    {
      title: "文心一格",
      desc: "百度推出的AI绘画平台",
      href: "https://tool.aiofchina.com/sites/569.html",
      url: "https://yige.baidu.com",
    },
    {
      title: "logoai",
      desc: "自动生成LOGO",
      href: "https://tool.aiofchina.com/sites/557.html",
      url: "https://www.logoai.com/logo-maker",
    },
    {
      title: "Hugging Face",
      desc: "Hugging Face 开发用于使用机器学习构建应用程序的工具。",
      href: "https://tool.aiofchina.com/sites/88.html",
      url: "https://huggingface.co/",
    },
    {
      title: "Booth.ai",
      desc: "使用 AI 创建专业品质的产品摄影",
      href: "https://tool.aiofchina.com/sites/49.html",
      url: "https://www.booth.ai/",
    },
    {
      title: "[完全免费]Draw Things",
      desc: "使用适用于 Mac 和 iOS 的 Stable Diffusion 的 AI 辅助图像生成。",
      href: "https://tool.aiofchina.com/sites/48.html",
      url: "https://drawthings.ai/",
    },
    {
      title: "[完全免费]diffusionbee",
      desc: "让您运行 Stable Diffuion 以生成 AI 艺术的 Mac 应用程序。",
      href: "https://tool.aiofchina.com/sites/47.html",
      url: "https://diffusionbee.com/",
    },
    {
      title: "Glazeroom",
      desc: "训练模型并以您自己独特的艺术风格生成任何东西。",
      href: "https://tool.aiofchina.com/sites/46.html",
      url: "https://glazeroom.com/",
    },
    {
      title: "Playground AI",
      desc: "使用 AI 和文本制作图形的最强大方式。",
      href: "https://tool.aiofchina.com/sites/45.html",
      url: "https://playgroundai.com/",
    },
    {
      title: "Astria",
      desc: "量身定制的AI图像生成",
      href: "https://tool.aiofchina.com/sites/44.html",
      url: "https://www.astria.ai/",
    },
    {
      title: "Lexica Search",
      desc: "Stable Diffusion搜索引擎",
      href: "https://tool.aiofchina.com/sites/41.html",
      url: "https://lexica.art",
    },
    {
      title: "[完全免费]Lexica Aperture",
      desc: "使用 Lexica Aperture 生成逼真的图像。",
      href: "https://tool.aiofchina.com/sites/40.html",
      url: "https://lexica.art",
    },
    {
      title: "[付费制]NovelAI",
      desc: "使用 Image Generation 可视化您最喜欢的角色。 借助领先的动漫艺术 AI 和其他 AI 模型，使用强大的图像模型来描绘故事中的人物和时刻。",
      href: "https://tool.aiofchina.com/sites/39.html",
      url: "https://novelai.net/",
    },
    {
      title: "Photo AI",
      desc: "上传照片、复制任何照片并在任何地方拍摄照片。",
      href: "https://tool.aiofchina.com/sites/38.html",
      url: "https://photoai.io/",
    },
    {
      title: "标小智",
      desc: "人工智能为您在线LOGO设计，生成企业VI，打造个性品牌！",
      href: "https://tool.aiofchina.com/sites/673.html",
      url: "https://www.logosc.cn",
    },
  ],
  图片修改: [
    {
      title: "petalica paint",
      desc: "线稿自动上色",
      href: "https://tool.aiofchina.com/sites/631.html",
      url: "https://petalica.com/index_zh.html",
    },
    {
      title: "神采",
      desc: "图生图，用草稿生成成品图",
      href: "https://tool.aiofchina.com/sites/624.html",
      url: "https://www.promeai.com",
    },
    {
      title: "人脸属性编辑-百度",
      desc: "对人脸属性特征进行编辑，实现性别互换、年龄改变等特效，为用户生成多种特效照片，可应用在趣味社交、短视频等娱乐场景",
      href: "https://tool.aiofchina.com/sites/613.html",
      url: "https://ai.baidu.com/tech/face/editattr",
    },
    {
      title: "ailabtools",
      desc: "通过人工智能算法，对人脸属性特征进行编辑，实现性别互换、年龄改变等特效，为用户生成多种特效照片，可应用在趣味社交。",
      href: "https://tool.aiofchina.com/sites/611.html",
      url: "https://www.ailabtools.com/zh-cn/age-gender-swap",
    },
    {
      title: "deep-nostalgia",
      desc: "Deep Nostalgia 是一款通过人工智能为老照片添加动态效果的工具，主要用于为家庭成员的老照片添加动画效果。你只需要上传一张照片，就可以看到人工智能对你的照片进行动画处理！",
      href: "https://tool.aiofchina.com/sites/609.html",
      url: "https://www.myheritage.jp/deep-nostalgia",
    },
    {
      title: "hitpaw",
      desc: "照片修复与增强",
      href: "https://tool.aiofchina.com/sites/597.html",
      url: "https://www.hitpaw.com/photo-enhancer.html",
    },
    {
      title: "Upscale.media",
      desc: "Upscale.media 使用 AI 技术自动将图片分辨率提升至原始尺寸的 4 倍，而不会对图片质量构成破坏。在将照片放大2倍或4倍的同时，去除JPEG伪影，消除素点或模糊的细节。这是一个简单且无成本的图片升级应用，如果你在 Midjourney、Lexica、Dalle2 或 Leanardo 中制作任何东西，并且希望它分辨率更大，则可以使用该应用程序。",
      href: "https://tool.aiofchina.com/sites/585.html",
      url: "https://www.upscale.media/zh",
    },
    {
      title: "waifu2x",
      desc: "本程序使用卷积神经网络对动漫风格的图片进行放大操作（支持照片）。",
      href: "https://tool.aiofchina.com/sites/225.html",
      url: "https://waifu2x.udp.jp",
    },
    {
      title: "[可试用]Clipdrop",
      desc: "一个由 AI 驱动的应用程序、插件和资源生态系统，供创作者使用。",
      href: "https://tool.aiofchina.com/sites/63.html",
      url: "https://clipdrop.co/",
    },
    {
      title: "Luminar",
      desc: "适用于 Mac 和 PC 的人工智能照片编辑器工具。",
      href: "https://tool.aiofchina.com/sites/62.html",
      url: "https://skylum.com/nl/luminar-ai",
    },
    {
      title: "Topaz Labs",
      desc: "使用 AI 提高您的照片和视频质量。",
      href: "https://tool.aiofchina.com/sites/61.html",
      url: "https://www.topazlabs.com/",
    },
    {
      title: "[可试用]BigJPG",
      desc: "放大图像而不会降低质量。",
      href: "https://tool.aiofchina.com/sites/60.html",
      url: "https://bigjpg.com/",
    },
    {
      title: "[可试用]AI Image Enlarger",
      desc: "多合一 AI 工具包可帮助您增强和提升图像质量。",
      href: "https://tool.aiofchina.com/sites/59.html",
      url: "https://imglarger.com/",
    },
    {
      title: "[完全免费]Unfake PNG",
      desc: "使背景变透明。",
      href: "https://tool.aiofchina.com/sites/58.html",
      url: "https://unfakepng.com/",
    },
    {
      title: "[可试用]RemoveBG",
      desc: "从图像中删除背景。",
      href: "https://tool.aiofchina.com/sites/57.html",
      url: "https://www.remove.bg/",
    },
    {
      title: "[可试用]]BG Eraser",
      desc: "使用 AI 移除对象并清理图片。",
      href: "https://tool.aiofchina.com/sites/56.html",
      url: "https://bgeraser.com",
    },
    {
      title: "[完全免费]Erase BG",
      desc: "免费从图像中删除背景",
      href: "https://tool.aiofchina.com/sites/55.html",
      url: "https://www.erase.bg/",
    },
    {
      title: "[完全免费]RestorePhotos.io",
      desc: "修复旧的和模糊的照片，让那些记忆得以延续。",
      href: "https://tool.aiofchina.com/sites/54.html",
      url: "https://www.restorephotos.io/",
    },
    {
      title: "[可试用]Viesus Cloud",
      desc: "基于云的 AI 解决方案，可增强和升级照片。",
      href: "https://tool.aiofchina.com/sites/53.html",
      url: "https://www.viesus.cloud/",
    },
    {
      title: "[可试用]Paint by Text",
      desc: "在 AI 的帮助下，使用书面说明编辑照片。",
      href: "https://tool.aiofchina.com/sites/52.html",
      url: "https://paintbytext.chat/",
    },
    {
      title: "[可试用]Mokker",
      desc: "人工智能背景更换",
      href: "https://tool.aiofchina.com/sites/51.html",
      url: "https://mokker.ai/",
    },
    {
      title: "Photoroom",
      desc: "使用多种 AI 编辑工具编辑您的照片。",
      href: "https://tool.aiofchina.com/sites/50.html",
      url: "https://www.photoroom.com/",
    },
    {
      title: "AI万能图片编辑器",
      desc: "在线修改图片颜色尺寸；智能抠图去水印；AI/EPS/PSD/SVG全格式支持的在线图片编辑器。",
      href: "https://tool.aiofchina.com/sites/671.html",
      url: "https://img.logosc.cn",
    },
  ],
  社交名片工具: [
    {
      title: "Lensa",
      desc: "构建照片和视频编辑的未来。",
      href: "https://tool.aiofchina.com/sites/71.html",
      url: "https://prisma-ai.com/",
    },
    {
      title: "[付费]Avatar AI",
      desc: "创建您自己的个人 AI 头像",
      href: "https://tool.aiofchina.com/sites/70.html",
      url: "https://avatarai.me/",
    },
    {
      title: "Profile Picture AI",
      desc: "创建您自己的逼真 AI 头像",
      href: "https://tool.aiofchina.com/sites/69.html",
      url: "https://www.profilepicture.ai/",
    },
    {
      title: "[可试用]Snapbar Headshots",
      desc: "为个人简化公司头像的头像解决方案",
      href: "https://tool.aiofchina.com/sites/68.html",
      url: "https://snapbar.com/professional-headshots-online",
    },
    {
      title: "[完全免费]Extrapolate",
      desc: "上传照片并了解您的年龄。",
      href: "https://tool.aiofchina.com/sites/67.html",
      url: "https://extrapolate.app/",
    },
    {
      title: "[付费]Hairstyle AI",
      desc: "使用人工智能生成不同的发型，看看哪一种最适合你。",
      href: "https://tool.aiofchina.com/sites/66.html",
      url: "https://www.hairstyleai.com/",
    },
    {
      title: "[有试用]AfterShoot",
      desc: "照片剔除变得简单",
      href: "https://tool.aiofchina.com/sites/64.html",
      url: "https://aftershoot.com/",
    },
  ],
  数据处理: [
    {
      title: "Scale",
      desc: "用于 AI 应用程序的高质量培训和验证数据。",
      href: "https://tool.aiofchina.com/sites/77.html",
      url: "https://scale.com/",
    },
    {
      title: "Abacus",
      desc: "支持大规模实时机器/深度学习的数据平台。",
      href: "https://tool.aiofchina.com/sites/76.html",
      url: "https://abacus.ai/",
    },
    {
      title: "Mason",
      desc: "用于数据分析的 AI 驱动的生产力应用程序。 查询、可视化和共享数据",
      href: "https://tool.aiofchina.com/sites/74.html",
      url: "https://mason.app/",
    },
    {
      title: "Rose",
      desc: "Rose 是一个云数据平台，可帮助用户查找、参与、可视化和共享数据。",
      href: "https://tool.aiofchina.com/sites/73.html",
      url: "https://rose.ai/",
    },
    {
      title: "String",
      desc: "与您的数据对话，无论数据位于何处或外观如何，您的数据都会对话。",
      href: "https://tool.aiofchina.com/sites/72.html",
      url: "https://www.askstring.com/",
    },
  ],
  AI模型开发平台: [
    {
      title: "tensor flow",
      desc: "它利用多层集线器的排列，使您能够快速设置、训练和发送具有庞大数据集的伪造神经系统。这就是让谷歌能够在其语音识别应用程序中识别照片中的问题或理解口头表达的词语的东西。",
      href: "https://tool.aiofchina.com/sites/496.html",
      url: "https://www.edureka.co/blog/tensorflow-tutorial/",
    },
    {
      title: "Hugging Face",
      desc: "Hugging Face 开发用于使用机器学习构建应用程序的工具。",
      href: "https://tool.aiofchina.com/sites/88.html",
      url: "https://huggingface.co/",
    },
    {
      title: "Muse",
      desc: "Google 的文本到图像生成/编辑模型",
      href: "https://tool.aiofchina.com/sites/87.html",
      url: "https://muse-model.github.io/",
    },
    {
      title: "Replicate",
      desc: "从您自己的代码在云中运行机器学习模型。",
      href: "https://tool.aiofchina.com/sites/86.html",
      url: "https://replicate.com/",
    },
    {
      title: "Stable Diffusion",
      desc: "一种深度学习模型，可根据文本描述生成详细图像。",
      href: "https://tool.aiofchina.com/sites/85.html",
      url: "https://stability.ai/",
    },
    {
      title: "Lightning AI",
      desc: "在云上快速构建 AI 产品、训练、微调和部署模型。",
      href: "https://tool.aiofchina.com/sites/84.html",
      url: "https://lightning.ai/",
    },
    {
      title: "Baseten",
      desc: "Baseten 是用于构建 ML 驱动的应用程序的无服务器后端。",
      href: "https://tool.aiofchina.com/sites/83.html",
      url: "https://www.baseten.co/",
    },
    {
      title: "No Code AI Model Builder",
      desc: "在几分钟内创建自定义 AI 模型，无需代码。",
      href: "https://tool.aiofchina.com/sites/82.html",
      url: "https://no-code-ai-model-builder.com/",
    },
    {
      title: "Humanloop",
      desc: "找到用户喜爱的提示并以更低的成本微调自定义模型。",
      href: "https://tool.aiofchina.com/sites/81.html",
      url: "https://humanloop.com/",
    },
    {
      title: "Diff Models",
      desc: "训练模型预测代码差异，训练来自 Github 的数百万次提交。",
      href: "https://tool.aiofchina.com/sites/80.html",
      url: "https://carper.ai/diff-models-a-new-way-to-edit-code",
    },
    {
      title: "Brancher",
      desc: "使用 Brancher 连接 AI 模型，无需代码即可构建功能强大的应用程序。",
      href: "https://tool.aiofchina.com/sites/79.html",
      url: "https://www.brancher.ai/",
    },
    {
      title: "[可试用]Banana",
      desc: "在无服务器 GPU 上扩展机器学习推理和训练。",
      href: "https://tool.aiofchina.com/sites/78.html",
      url: "https://www.banana.dev/",
    },
  ],
  程序开发: [
    {
      title: "gpt-engineer",
      desc: "Specify what you want it to build, the AI asks for clarification, and then builds it.  GPT Engineer is made to be easy to adapt, extend, and make your agent learn how you want your code to look. It generates an entire codebase based on a prompt.",
      href: "https://tool.aiofchina.com/sites/691.html",
      url: "https://github.com/AntonOsika/gpt-engineer",
    },
    {
      title: "[可试用]Github CoPilot AI pair programmer",
      desc: "Copilot 在您的代码编辑器中为您建议整行或整个功能。",
      href: "https://tool.aiofchina.com/sites/105.html",
      url: "https://github.com/features/copilot",
    },
    {
      title: "[开源]PLZ-CLI",
      desc: "使用自然语言查找终端命令",
      href: "https://tool.aiofchina.com/sites/104.html",
      url: "https://github.com/m1guelpf/plz-cli",
    },
    {
      title: "Ask Command",
      desc: "一个小应用程序，可以提醒您那些您总是忘记的命令。",
      href: "https://tool.aiofchina.com/sites/103.html",
      url: "https://askcommand.com/",
    },
    {
      title: "What The Diff",
      desc: "通过自动化拉取请求摘要来节省昂贵的开发人员时间。",
      href: "https://tool.aiofchina.com/sites/102.html",
      url: "https://whatthediff.ai/",
    },
    {
      title: "Codeball",
      desc: "Codeball 使用 AI 在您的合并请求中查找错误。",
      href: "https://tool.aiofchina.com/sites/101.html",
      url: "https://codeball.ai/",
    },
    {
      title: "ExplainDev",
      desc: "解释代码并直接回答您的技术问题。",
      href: "https://tool.aiofchina.com/sites/100.html",
      url: "https://explain.dev/",
    },
    {
      title: "Ghostwriter",
      desc: "Replit 的 Ghostwriter 使用 AI 帮助您更快地编写更好的代码。",
      href: "https://tool.aiofchina.com/sites/99.html",
      url: "https://replit.com/site/ghostwriter",
    },
    {
      title: "HTTPie AI",
      desc: "在测试和与 API 对话时，使用 AI 提高您的工作效率。",
      href: "https://tool.aiofchina.com/sites/98.html",
      url: "https://httpie.io/ai",
    },
    {
      title: "AI Query",
      desc: "使用简单的英文，让AI秒生成无错SQL。",
      href: "https://tool.aiofchina.com/sites/97.html",
      url: "https://aiquery.co/",
    },
    {
      title: "AirOps",
      desc: "使用一组强大的方法编写 SQL、文档等。",
      href: "https://tool.aiofchina.com/sites/96.html",
      url: "https://www.airops.com/",
    },
    {
      title: "Debuild",
      desc: "人工智能驱动的低代码工具，可帮助您以极快的​​速度构建 Web 应用程序。",
      href: "https://tool.aiofchina.com/sites/95.html",
      url: "https://debuild.app/",
    },
    {
      title: "co:here",
      desc: "帮助开发人员制作读写程序的工具包。",
      href: "https://tool.aiofchina.com/sites/94.html",
      url: "https://cohere.ai/",
    },
    {
      title: "SpellBox",
      desc: "SpellBox 使用人工智能从简单的提示中创建您需要的代码。",
      href: "https://tool.aiofchina.com/sites/93.html",
      url: "https://spellbox.app/",
    },
    {
      title: "[免费]Auto Backend",
      desc: "仅需几句话即可创建 AI 生成的后端。",
      href: "https://tool.aiofchina.com/sites/92.html",
      url: "https://www.autobackend.dev/",
    },
    {
      title: "Bifrost",
      desc: "使用 AI 将您的 Figma 设计自动转换为干净的 React 代码。",
      href: "https://tool.aiofchina.com/sites/91.html",
      url: "https://www.bifrost.so/",
    },
    {
      title: "HeyCLI",
      desc: "使用 HeyCLI 将自然语言翻译成终端命令。",
      href: "https://tool.aiofchina.com/sites/90.html",
      url: "https://www.heycli.com/",
    },
    {
      title: "[可试用]Code Snippets",
      desc: "使用 GPT3 生成、重构、调试和记录您的代码片段。",
      href: "https://tool.aiofchina.com/sites/89.html",
      url: "https://codesnippets.ai/",
    },
  ],
  语音转文字: [
    {
      title: "Easysub",
      desc: " 易于使用的 EasySub 自动字幕生成器",
      href: "https://tool.aiofchina.com/sites/694.html",
      url: "https://easyssub.com",
    },
  ],
  文字转语音: [
    {
      title: "Azure Speech",
      desc: "用听起来自然的声音让您的应用程序栩栩如生。",
      href: "https://tool.aiofchina.com/sites/146.html",
      url: "https://azure.microsoft.com/en-us/products/cognitive-services/text-to-speech/",
    },
    {
      title: "讯飞智作",
      desc: "让你的音视频创作更快、更省、更独特",
      href: "https://tool.aiofchina.com/sites/629.html",
      url: "https://peiyin.xunfei.cn",
    },
    {
      title: "speechify",
      desc: "Speechify 可以将任何格式的文本转换为听起来自然的语音。该平台基于网络，可以将 PDF、电子邮件、文档或文章转换为可以收听而不是阅读的音频",
      href: "https://tool.aiofchina.com/sites/601.html",
      url: "https://speechify.com/",
    },
    {
      title: "Whisper",
      desc: "接近人类水平鲁棒性和准确性的神经网络。",
      href: "https://tool.aiofchina.com/sites/152.html",
      url: "https://openai.com/blog/whisper/",
    },
    {
      title: "Resemble",
      desc: "在几秒钟内生成类似人类的配音。",
      href: "https://tool.aiofchina.com/sites/151.html",
      url: "https://www.resemble.ai/",
    },
    {
      title: "Play.HT",
      desc: "人工智能驱动的文本到语音生成器",
      href: "https://tool.aiofchina.com/sites/150.html",
      url: "https://play.ht/",
    },
    {
      title: "Apple Audiobooks",
      desc: "有声读物的 Apple Books 数字旁白。",
      href: "https://tool.aiofchina.com/sites/149.html",
      url: "https://authors.apple.com/support/4519-digital-narration-audiobooks",
    },
    {
      title: "Voice.ai",
      desc: "Voice.ai 是一款免费的实时语音转换器，可在应用程序和游戏中使用。",
      href: "https://tool.aiofchina.com/sites/148.html",
      url: "https://voice.ai/",
    },
    {
      title: "WellSaid",
      desc: "为您的所有数字内容创建引人入胜的逼真 AI 配音",
      href: "https://tool.aiofchina.com/sites/147.html",
      url: "https://wellsaidlabs.com/",
    },
    {
      title: "Coqui",
      desc: "用于视频游戏、后期制作等的直接情感生成 AI 声音。",
      href: "https://tool.aiofchina.com/sites/145.html",
      url: "https://coqui.ai/",
    },
    {
      title: "Murf",
      desc: "使用多功能 AI 语音生成器从文本到语音。",
      href: "https://tool.aiofchina.com/sites/144.html",
      url: "https://murf.ai/",
    },
    {
      title: "Supertone",
      desc: "使用歌唱和表演语音分离 AI 技术产生超逼真的效果。",
      href: "https://tool.aiofchina.com/sites/143.html",
      url: "https://supertone.ai/",
    },
    {
      title: "Uberduck",
      desc: "开源 AI 语音社区，可让您从文本生成语音。",
      href: "https://tool.aiofchina.com/sites/142.html",
      url: "https://uberduck.ai/",
    },
  ],
  视频处理: [
    {
      title: "Segment Anything Model",
      desc: "Segment Anything Model (SAM)：一种来自 Meta AI 的新 AI 模型，只需单击一下即可“切出”任何图像中的任何对象",
      href: "https://tool.aiofchina.com/sites/651.html",
      url: "https://segment-anything.com",
    },
  ],
  视频生成: [
    {
      title: "pictory",
      desc: "从您的长篇内容中自动创建简短的、高度共享的品牌视频。",
      href: "https://tool.aiofchina.com/sites/593.html",
      url: "https://pictory.ai/",
    },
    {
      title: "Quickvid",
      desc: "制作youtube视频的速度加快10倍",
      href: "https://tool.aiofchina.com/sites/559.html",
      url: "https://www.quickvid.ai",
    },
    {
      title: "Runway",
      desc: "探索视频编辑功能，让您的创作更上一层楼。",
      href: "https://tool.aiofchina.com/sites/122.html",
      url: "https://runwayml.com/",
    },
    {
      title: "SkipVid",
      desc: "一键跳过 Youtube 视频。",
      href: "https://tool.aiofchina.com/sites/121.html",
      url: "https://skipvid.herokuapp.com/",
    },
    {
      title: "Descript",
      desc: "多合一的视频和音频编辑，就像文档一样简单。",
      href: "https://tool.aiofchina.com/sites/120.html",
      url: "https://www.descript.com/",
    },
    {
      title: "CreatorML",
      desc: "YouTube 的视频标题和缩略图排序器",
      href: "https://tool.aiofchina.com/sites/119.html",
      url: "https://creatorml.com/",
    },
    {
      title: "Synthesia",
      desc: "在几分钟内从纯文本创建视频",
      href: "https://tool.aiofchina.com/sites/118.html",
      url: "https://www.synthesia.io/",
    },
    {
      title: "Detail",
      desc: "在几分钟内录制、重新混合和分享鼓舞人心的视频。",
      href: "https://tool.aiofchina.com/sites/117.html",
      url: "https://detail.co/",
    },
    {
      title: "Fliki",
      desc: "在 2 分钟内根据脚本或博客文章创建视频（带声音）。",
      href: "https://tool.aiofchina.com/sites/116.html",
      url: "https://fliki.ai/",
    },
    {
      title: "Flawless",
      desc: "使用突破性的 AI 以视觉方式将电影和电视翻译成任何语言。",
      href: "https://tool.aiofchina.com/sites/115.html",
      url: "https://www.flawlessai.com/",
    },
    {
      title: "Move",
      desc: "适合所有人的改变游戏规则的高保真无标记动作捕捉。",
      href: "https://tool.aiofchina.com/sites/114.html",
      url: "https://www.move.ai/",
    },
    {
      title: "Genmo",
      desc: "通过创建视频、动画等，超越 Genmo 上的 2D 图像。",
      href: "https://tool.aiofchina.com/sites/113.html",
      url: "https://alpha.genmo.ai/",
    },
    {
      title: "Poised",
      desc: "人工智能驱动的沟通教练，帮助您自信、清晰地说话。",
      href: "https://tool.aiofchina.com/sites/112.html",
      url: "https://www.poised.com/",
    },
    {
      title: "[免费]Eightify",
      desc: "使用此 Chrome 扩展为 YouTube 视频生成摘要。",
      href: "https://tool.aiofchina.com/sites/111.html",
      url: "https://eightify.app/",
    },
    {
      title: "[免费]Dreamix",
      desc: "Dreamix 编辑视频，同时保持颜色、姿势、对象大小和相机姿势。",
      href: "https://tool.aiofchina.com/sites/110.html",
      url: "https://dreamix-video-editing.github.io/",
    },
    {
      title: "Morise",
      desc: "当您专注于创建有意义的内容时，让 AI 为算法操心。",
      href: "https://tool.aiofchina.com/sites/109.html",
      url: "https://morise.ai/",
    },
    {
      title: "Thumbnail Face",
      desc: "上传您的图像并立即获得去除背景、裁剪、突出显示的面孔。",
      href: "https://tool.aiofchina.com/sites/108.html",
      url: "https://thumbnailface.com/",
    },
    {
      title: "Vowel",
      desc: "远程团队主持、总结、搜索和共享视频会议的工具。",
      href: "https://tool.aiofchina.com/sites/107.html",
      url: "https://www.vowel.com/",
    },
    {
      title: "Dumme",
      desc: "使用 AI 生成可随时上传的带字幕视频短片，无需编辑。",
      href: "https://tool.aiofchina.com/sites/106.html",
      url: "https://dumme.com/",
    },
  ],
  自媒体录制: [
    {
      title: "Anypod",
      desc: "用于 YouTube/Podcast 内容的语义搜索引擎。",
      href: "https://tool.aiofchina.com/sites/125.html",
      url: "https://www.anypod.ai/",
    },
    {
      title: "Adobe Podcast",
      desc: "来自 Adob​​e 的下一代音频就在这里。 记录、转录、编辑、分享。 每次都清晰明了。",
      href: "https://tool.aiofchina.com/sites/124.html",
      url: "https://podcast.adobe.com/",
    },
    {
      title: "Huberman AI",
      desc: "用人工智能探索休伯曼实验室的智慧。",
      href: "https://tool.aiofchina.com/sites/123.html",
      url: "https://huberman.rile.yt/",
    },
  ],
  音频处理: [
    {
      title: "deepbeat",
      desc: "DeepBeat 是一个歌词生成 AI 工具，它可以根据你输入的第一句歌词和说唱主题生成押韵的歌词。它非常易于使用，是一个非常有趣的AI 玩具！  DeepBeat是完全免费的，不需要任何登录或注册。",
      href: "https://tool.aiofchina.com/sites/607.html",
      url: "https://deepbeat.org",
    },
    {
      title: "ElevenLabs",
      desc: "ElevenLabs 是一家语音技术研究企业，开发了一款非常有影响力的人工智能语音软件。ElevenLabs AI 软件的深度学习算法实现了与人类高度相似的语调和语音转变，还能根据情况调整讲话语调。有了这个最前沿、最通用的人工智能语音工具，用户可以用简单的文本制作任何声音和风格的高质量音频内容。",
      href: "https://tool.aiofchina.com/sites/587.html",
      url: "https://beta.elevenlabs.io",
    },
    {
      title: "AIVA",
      desc: "AI智能作曲",
      href: "https://tool.aiofchina.com/sites/520.html",
      url: "https://www.aiva.ai",
    },
    {
      title: "soundraw",
      desc: "AI自动创作音乐",
      href: "https://tool.aiofchina.com/sites/518.html",
      url: "https://soundraw.io",
    },
    {
      title: "Synth",
      desc: "一款适用于所有会议、播客和其他实时音频的智能工具。",
      href: "https://tool.aiofchina.com/sites/132.html",
      url: "https://usesynth.com/",
    },
    {
      title: "LALAL.AI",
      desc: "从任何音频和视频中提取人声、伴奏和各种乐器。",
      href: "https://tool.aiofchina.com/sites/131.html",
      url: "https://www.lalal.ai/",
    },
    {
      title: "Audyo",
      desc: "使用 AI 在几分钟内将您的书面内容转换为人类品质的音频。",
      href: "https://tool.aiofchina.com/sites/130.html",
      url: "https://www.audyo.ai/",
    },
    {
      title: "AssemblyAI",
      desc: "通过我们简单的 API 访问强大的音频 AI 模型。",
      href: "https://tool.aiofchina.com/sites/129.html",
      url: "https://www.assemblyai.com/",
    },
    {
      title: "Splitter",
      desc: "使用机器学习从歌曲中分离乐器。",
      href: "https://tool.aiofchina.com/sites/128.html",
      url: "https://splitter.ai/",
    },
    {
      title: "Cleanvoice",
      desc: "从音频中删除填充音、口吃和口音。",
      href: "https://tool.aiofchina.com/sites/127.html",
      url: "https://cleanvoice.ai/",
    },
    {
      title: "[开源]MusicLM",
      desc: "Google 的一种模型，可根据文本描述生成高保真音乐。",
      href: "https://tool.aiofchina.com/sites/126.html",
      url: "https://google-research.github.io/seanet/musiclm/examples/",
    },
  ],
  AI作曲: [
    {
      title: "suno【AI作曲唱歌】",
      desc: "AI自动作曲唱歌",
      href: "https://tool.aiofchina.com/sites/753.html",
      url: "https://suno.com/",
    },
  ],
  AI搜索引擎: [
    {
      title: "New Bing",
      desc: "提出真正的问题。获得完整的答案。聊天并创建。",
      href: "https://tool.aiofchina.com/sites/233.html",
      url: "https://www.bing.com/new",
    },
    {
      title: "Lexica",
      desc: "Lexica 搜索引擎可使用 Stable Diffusio 模型来创建AI图片，同时提供搜索功能。为了形成逼真的视觉效果，模型首先使用搜索引擎找到高质量的文本提示，而这些提示是从大量图片文本资料中寻找的，在语义上与搜索的内容相关，方便用户知道要怎么描述才能产生想要的图片",
      href: "https://tool.aiofchina.com/sites/591.html",
      url: "https://lexica.art",
    },
    {
      title: "Waldo",
      desc: "网络搜索速度提高 2 倍。 Waldo 是在线查找高质量信息的最快方式。使用网络上最好的资源，将您花在研究上的时间减半。",
      href: "https://tool.aiofchina.com/sites/507.html",
      url: "https://www.waldo.fyi",
    },
    {
      title: "Andi",
      desc: "你好！我是安迪，你的智能搜索助手。你的问题越详细我越能帮到你?",
      href: "https://tool.aiofchina.com/sites/505.html",
      url: "https://andisearch.com",
    },
    {
      title: "Rewind",
      desc: "Rewind 记录您看到、说过或听到的任何内容，并使其可供搜索。",
      href: "https://tool.aiofchina.com/sites/141.html",
      url: "https://www.rewind.ai/",
    },
    {
      title: "Perplexity",
      desc: "使用 OpenAI GPT 3.5 和 Microsoft Bing 的搜索界面。",
      href: "https://tool.aiofchina.com/sites/140.html",
      url: "https://www.perplexity.ai/",
    },
    {
      title: "Neeva",
      desc: "使用尖端的 LLM 和独立的搜索堆栈进行真实的实时 AI 搜索。",
      href: "https://tool.aiofchina.com/sites/139.html",
      url: "https://neeva.com/blog/introducing-neevaai",
    },
    {
      title: "Phind",
      desc: "基于它自己的大型语言模型的 AI 搜索引擎。",
      href: "https://tool.aiofchina.com/sites/138.html",
      url: "https://phind.com/",
    },
    {
      title: "Cherrry",
      desc: "使用自然语言查询文本、图像和音频的简单 API。",
      href: "https://tool.aiofchina.com/sites/137.html",
      url: "https://www.cherrry.com/",
    },
    {
      title: "You",
      desc: "You.com 是一个人工智能驱动的隐私搜索引擎。",
      href: "https://tool.aiofchina.com/sites/136.html",
      url: "https://you.com/",
    },
    {
      title: "Hebbia",
      desc: "借助 AI 驱动的洞察力，更自信、更快速地做出 10 倍的决策。",
      href: "https://tool.aiofchina.com/sites/133.html",
      url: "https://www.hebbia.ai/",
    },
  ],
  棋牌游戏: [
    {
      title: "Katago",
      desc: "开源版之中最强大的围棋软件",
      href: "https://tool.aiofchina.com/sites/442.html",
      url: "https://github.com/yzyray/lizzieyzy",
    },
    {
      title: "星阵围棋",
      desc: "国家队职业棋手使用的最强围棋AI，需要付费使用",
      href: "https://tool.aiofchina.com/sites/444.html",
      url: "https://19x19.com",
    },
    {
      title: "扑克AI – 德州扑克人工智能",
      desc: "德州扑克AI",
      href: "https://tool.aiofchina.com/sites/452.html",
      url: "https://apps.apple.com/cn/app/%E6%89%91%E5%85%8Bai-%E5%BE%B7%E5%B7%9E%E6%89%91%E5%85%8B%E4%BA%BA%E5%B7%A5%E6%99%BA%E8%83%BD/id1553727514",
    },
    {
      title: "stockfish",
      desc: "最强大的开源版国际象棋软件",
      href: "https://tool.aiofchina.com/sites/450.html",
      url: "https://stockfishchess.org",
    },
    {
      title: "皮卡鱼",
      desc: "中国象棋开源版最强AI",
      href: "https://tool.aiofchina.com/sites/446.html",
      url: "http://pikafish.org",
    },
  ],
  法律咨询: [
    {
      title: "AI 法律助手",
      desc: "法律文件来源：https://github.com/LawRefBook/Laws  项目模板：https://github.com/supabase-community/nextjs-openai-doc-search  这个项目从 pages 目录中获取所有的 .mdx 文件，并将其处理成自定义上下文，以在OpenAI 文本自动补全提示中使用。",
      href: "https://tool.aiofchina.com/sites/655.html",
      url: "https://github.com/lvwzhen/law-cn-ai",
    },
    {
      title: "legalrobot",
      desc: "为所有人提供自动化的法律咨询服务",
      href: "https://tool.aiofchina.com/sites/474.html",
      url: "https://legalrobot.com",
    },
    {
      title: "Detangle",
      desc: "上传您的法律文件并将其翻译成人类可读的文本",
      href: "https://tool.aiofchina.com/sites/219.html",
      url: "https://detangle.ai/",
    },
  ],
  电子邮件: [
    {
      title: "Ellie – Your AI Email Assistant",
      desc: "Ellie 从您的写作风格中学习，并像您写的一样精心回复",
      href: "https://tool.aiofchina.com/sites/157.html",
      url: "https://tryellie.com/",
    },
    {
      title: "Addy AI",
      desc: "电子邮件助理，可在几秒钟内以您喜欢的风格和语气起草您的电子邮件。",
      href: "https://tool.aiofchina.com/sites/156.html",
      url: "https://addy-ai.web.app/",
    },
    {
      title: "EmailTriager",
      desc: "使用 AI 在后台自动起草电子邮件回复。",
      href: "https://tool.aiofchina.com/sites/155.html",
      url: "https://www.emailtriager.com/",
    },
    {
      title: "[可试用]Warmer AI",
      desc: "Sky 使用 AI 生成的独特个性化设置让您的冷邮件大放异彩。",
      href: "https://tool.aiofchina.com/sites/154.html",
      url: "https://warmer.ai/",
    },
  ],
  写作文案: [
    {
      title: "百度作家平台",
      desc: "免费AI小说写作",
      href: "https://tool.aiofchina.com/sites/737.html",
      url: "https://zuojia.baidu.com/",
    },
    {
      title: "Notion AI",
      desc: "使用Notion AI大幅提高生产力",
      href: "https://tool.aiofchina.com/sites/455.html",
      url: "https://www.notion.so/product/ai",
    },
    {
      title: "一帧秒创-国产AI创作平台",
      desc: "秒创AI帮写基于人工智能模型,帮您瞬间完成视频文案创作,让您生产视频更高效、有趣！",
      href: "https://tool.aiofchina.com/sites/640.html",
      url: "https://aigc.yizhentv.com/",
    },
    {
      title: "WPS智能写作",
      desc: "颠覆传统写作模式  开启AI智能写作时代",
      href: "https://tool.aiofchina.com/sites/635.html",
      url: "https://aiwrite.wps.cn/#/",
    },
    {
      title: "neuraltext",
      desc: "Neuraltext 旨在使用 AI 涵盖从构思到执行的整个内容流程。  它是一个 AI 撰稿人、SEO 内容工具和关键字研究工具。  AI 文案撰写工具可让您为您的活动创建有效的文案，生成数十种变体。它有 50 多个随时可用的模板（Facebook 广告、口号创意、博客部分写作等）。",
      href: "https://tool.aiofchina.com/sites/603.html",
      url: "https://www.neuraltext.com/",
    },
    {
      title: "[付费]Giiso",
      desc: "写作机器人",
      href: "https://tool.aiofchina.com/sites/561.html",
      url: "https://www.giiso.com/#/",
    },
    {
      title: "AI简历",
      desc: "AI简历-海量简历模板,15分钟快速制作简历",
      href: "https://tool.aiofchina.com/sites/541.html",
      url: "https://www.chzhkeji.com",
    },
    {
      title: "writer",
      desc: "Writer 从构思开始加速您的写作流程 ",
      href: "https://tool.aiofchina.com/sites/527.html",
      url: "https://writer.com",
    },
    {
      title: "[仅限英文]AI-Writer",
      desc: "AI-Writer 是最准确的内容生成平台，使用最先进的 AI 写作模型从标题生成文章。",
      href: "https://tool.aiofchina.com/sites/525.html",
      url: "https://ai-writer.com",
    },
    {
      title: "写作猫",
      desc: "写作猫智能写作软件是AITEXT一款专为写作者量身定制的工具，此外，我们还提供免费的查词服务，帮助用户更好地理解和使用语言。",
      href: "https://tool.aiofchina.com/sites/523.html",
      url: "http://www.aixzzs.com",
    },
    {
      title: "抖音AI文案",
      desc: "抖音ai文案自动生成器",
      href: "https://tool.aiofchina.com/sites/516.html",
      url: "https://www.douyin.com/zhuanti/7183045778179459132",
    },
    {
      title: "simplified",
      desc: "使用 AI 文案，在几秒钟内生成 50 多种类型的文案。使用 Simplified 的免费内容编写工具为视频、广告、报价、产品、博客、文章等创建独一无二的文本。",
      href: "https://tool.aiofchina.com/sites/514.html",
      url: "https://simplified.com/zh-ai-writer/",
    },
    {
      title: "[免费试用]Hypotenuse AI",
      desc: "人工智慧文案生成器",
      href: "https://tool.aiofchina.com/sites/511.html",
      url: "https://zh.hypotenuse.ai/%E4%BA%BA%E5%B7%A5%E6%99%BA%E6%85%A7%E6%96%87%E6%A1%88%E7%94%9F%E6%88%90%E5%99%A8",
    },
    {
      title: "Neuraltext",
      desc: "Neuraltext 旨在使用 AI 涵盖从构思到执行的整个内容流程。它是一个 AI 撰稿人、SEO 内容工具和关键字研究工具。",
      href: "https://tool.aiofchina.com/sites/472.html",
      url: "https://www.neuraltext.com/",
    },
    {
      title: "AIssistify",
      desc: "制作更好的广告。 更快地回复客户。 生成您的下一个营销创意。",
      href: "https://tool.aiofchina.com/sites/196.html",
      url: "https://aissistify.com/",
    },
  ],
  电子表格: [
    {
      title: "SheetGod",
      desc: "几秒钟把英文变成Excel公式的AI工具。",
      href: "https://tool.aiofchina.com/sites/165.html",
      url: "https://www.boloforms.com/",
    },
    {
      title: "SheetAI",
      desc: "使用 SheetAI 在您的电子表格中释放 AI 的力量。",
      href: "https://tool.aiofchina.com/sites/164.html",
      url: "https://www.sheetai.app/",
    },
    {
      title: "Formula God",
      desc: "与内置人工智能的电子表格对话。",
      href: "https://tool.aiofchina.com/sites/163.html",
      url: "https://www.formulagod.ai/",
    },
    {
      title: "NeuralFormula",
      desc: "使用人工智能增强您的电子表格。",
      href: "https://tool.aiofchina.com/sites/162.html",
      url: "https://www.neuralformula.com/",
    },
    {
      title: "SheetPlus",
      desc: "在 AI 的帮助下更快地编写 Google 表格和 Excel 公式。",
      href: "https://tool.aiofchina.com/sites/161.html",
      url: "https://sheetplus.ai/",
    },
    {
      title: "Excelformulabot",
      desc: "在几秒钟内将您的文本指令转换为 Excel 公式。",
      href: "https://tool.aiofchina.com/sites/160.html",
      url: "https://excelformulabot.com/",
    },
    {
      title: "Jeeves",
      desc: "提出问题，获得答案，无需电子表格公式。",
      href: "https://tool.aiofchina.com/sites/159.html",
      url: "https://www.therocketbrew.com/",
    },
    {
      title: "Charm",
      desc: "Charm 可以生成、转换和分析 Google 表格中的任何文本数据。",
      href: "https://tool.aiofchina.com/sites/158.html",
      url: "https://usecharm.ai/",
    },
  ],
  求职助理: [
    {
      title: "AI简历-量身定制的求职帮手",
      desc: "简单三步，在数秒钟生成量身定制的高质量简历。使用简历优化提高简历质量，让HR无法抗拒，轻松斩获Offer，免费使用简历模板。",
      href: "https://tool.aiofchina.com/sites/741.html",
      url: "https://ai-tools.cn/resume",
    },
  ],
  游戏开发: [
    {
      title: "opus",
      desc: "一款将文本转换为视频游戏的AI应用。OPUS利用机器学习(ML)和自然语言处理(NLP)策略，可以根据文本描述来自动创建视频游戏的场景。此外，OPUS可以通过评估故事或游戏场景的文本，自动生成补充叙事的游戏机制、设置和人物，其他人和AI应用都可以参与到最终的游戏构造中。",
      href: "https://tool.aiofchina.com/sites/577.html",
      url: "https://opus.ai",
    },
    {
      title: "Scenario",
      desc: "为您的游戏生成高质量、风格一致的专有资产。",
      href: "https://tool.aiofchina.com/sites/168.html",
      url: "https://www.scenario.gg/",
    },
    {
      title: "Modl",
      desc: "部署可在您的游戏中玩耍、成长和学习的 AI 和 ML 机器人。",
      href: "https://tool.aiofchina.com/sites/167.html",
      url: "https://modl.ai/",
    },
    {
      title: "Moonlander",
      desc: "在几天而不是几个月内开始构建高质量的 3D 游戏和世界。",
      href: "https://tool.aiofchina.com/sites/166.html",
      url: "http://moonlander.ai/",
    },
  ],
  AI客服: [
    {
      title: "genesys",
      desc: "Genesys是一种智能网络聊天机器人，它使用 NLP 来了解客户的意图。它不需要任何关键字匹配，并且可以在响应用户时记住整个对话。它以自然的方式回答问题，同时还允许客户通过聊天机器人购买产品。 ",
      href: "https://tool.aiofchina.com/sites/477.html",
      url: "https://www.genesys.com/genesys-cloud",
    },
    {
      title: "Eddy AI",
      desc: "Eddy AI 是一款由人工智能驱动的全自动聊天机器人。",
      href: "https://tool.aiofchina.com/sites/173.html",
      url: "https://eddyai.com/",
    },
    {
      title: "Resolve AI",
      desc: "利用 AI 聊天机器人提供 24/7 全天候自动化客户支持。",
      href: "https://tool.aiofchina.com/sites/172.html",
      url: "https://resolveai.co/",
    },
    {
      title: "Cohere",
      desc: "在不增加员工人数的情况下更快地解决工单，同时降低成本。",
      href: "https://tool.aiofchina.com/sites/171.html",
      url: "https://cohere.io/",
    },
    {
      title: "Fini",
      desc: "根据您的知识库生成一个 AI 客服，准备好回答你的问题。您提供您的文档的链接。",
      href: "https://tool.aiofchina.com/sites/33.html",
      url: "https://www.usefini.com/",
    },
  ],
  行政助理: [
    {
      title: "通义听悟",
      desc: "[通义听悟」是通义家族新成员，依托通义千问语言模型、音视频AI模型能力，为用户带来音频和视频内容记录和阅读的全新体验。",
      href: "https://tool.aiofchina.com/sites/677.html",
      url: "https://tingwu.aliyun.com",
    },
    {
      title: "Textio",
      desc: "Textio 是一种人工智能工具，它依靠预测技术来改进职位列表。它分析每个单词，识别 5,000 多个短语，并根据文档吸引用户的能力对文档进行评分。同时，该工具通过在职位描述中检测性别偏见来帮助消除招聘过程中的性别偏见。Textio 被 Twitter、微软、Square 和星巴克等大公司使用。",
      href: "https://tool.aiofchina.com/sites/488.html",
      url: "https://textio.com",
    },
    {
      title: "Augmentir",
      desc: "Augmentir 针对的是工业公司。它是一套由人工智能驱动的互联员工工具，有助于提高一线员工的安全性、生产力和质量。通过基于人类活动数据提供对运营的深入洞察，公司可以确定在生产力、质量和降低成本方面可以改进的地方。 ",
      href: "https://tool.aiofchina.com/sites/484.html",
      url: "https://www.augmentir.com/lp/demo",
    },
    {
      title: "Fireflies",
      desc: "Fireflies是一个 AI 会议助手，它使用 NLP 来消除在会议期间做笔记的需要。在直观易用的平台上轻松录制、转录和搜索语音对话。",
      href: "https://tool.aiofchina.com/sites/470.html",
      url: "https://fireflies.ai/",
    },
    {
      title: "Reclaim",
      desc: "Reclaim 为您的优先事项创建完美的时间表，为您节省高达 40% 的每周工作时间。",
      href: "https://tool.aiofchina.com/sites/210.html",
      url: "https://reclaim.ai/",
    },
  ],
  翻译: [
    {
      title: "Alexa Translations",
      desc: "打破语言壁垒",
      href: "https://tool.aiofchina.com/sites/553.html",
      url: "https://alexatranslations.com",
    },
    {
      title: "DeepL",
      desc: "准确的翻译服务，即使是最细微的差别也能捕捉到。",
      href: "https://tool.aiofchina.com/sites/174.html",
      url: "https://www.deepl.com/translator",
    },
  ],
  APP: [
    {
      title: "Rizz!",
      desc: "适用于您的 iPhone 的 AI 键盘，可用于任何其他应用程序。",
      href: "https://tool.aiofchina.com/sites/177.html",
      url: "https://apps.apple.com/us/app/rizz/id1661403200",
    },
    {
      title: "AI Photo for iPhone",
      desc: "在您的 iPhone 上运行 Stable Diffusion 并随时随地生成图像。",
      href: "https://tool.aiofchina.com/sites/176.html",
      url: "https://apps.apple.com/app/id6444911377",
    },
    {
      title: "Historical Figures",
      desc: "使用 AI 与 20,000 多个过去的历史人物进行对话。",
      href: "https://tool.aiofchina.com/sites/175.html",
      url: "https://apps.apple.com/nl/app/historical-figures-chat/id6444197650",
    },
  ],
  "3D": [
    {
      title: "Lumalabs",
      desc: "使用人工智能在 3D 中捕获和设置关键帧。",
      href: "https://tool.aiofchina.com/sites/183.html",
      url: "https://lumalabs.ai/",
    },
    {
      title: "[开源]OpenAI Point-E",
      desc: "用于根据复杂提示生成 3D 点云的系统。",
      href: "https://tool.aiofchina.com/sites/182.html",
      url: "https://github.com/openai/point-e",
    },
    {
      title: "Masterpiece Studio",
      desc: "使用生成式人工智能轻松制作 3D。",
      href: "https://tool.aiofchina.com/sites/181.html",
      url: "https://masterpiecestudio.com/",
    },
    {
      title: "Plask",
      desc: "人工智能驱动的动作捕捉动画工具可处理 3D 运动。",
      href: "https://tool.aiofchina.com/sites/180.html",
      url: "https://plask.ai/",
    },
    {
      title: "[开源]Make A Video 3D",
      desc: "一种从文本描述生成三维动态场景的方法。",
      href: "https://tool.aiofchina.com/sites/179.html",
      url: "https://make-a-video3d.github.io/",
    },
    {
      title: "Mirage",
      desc: "AI 驱动的 3D 画布让创意者可以轻松设计美丽的环境。",
      href: "https://tool.aiofchina.com/sites/178.html",
      url: "https://www.mirageml.com/",
    },
  ],
  简报生成: [
    {
      title: "Tome – The storytelling tool for work.",
      desc: "停止设计幻灯片，开始讲故事。",
      href: "https://tool.aiofchina.com/sites/195.html",
      url: "https://beta.tome.app/",
    },
    {
      title: "[完全免费]ChatBCG",
      desc: "ChatBCG 可以使用文本描述生成幻灯片。",
      href: "https://tool.aiofchina.com/sites/194.html",
      url: "https://www.chatba.com/",
    },
    {
      title: "Slides AI",
      desc: "立即从任何文本创建专业、引人入胜的幻灯片。",
      href: "https://tool.aiofchina.com/sites/193.html",
      url: "https://www.slidesai.io/",
    },
  ],
  金融财会: [
    {
      title: "FinChat",
      desc: "finchat是一个面向投资者的chatgpt",
      href: "https://tool.aiofchina.com/sites/706.html",
      url: "https://finchat.io",
    },
    {
      title: "Tickeron",
      desc: "Tickeron 提供了很多很棒的功能，例如 AI 趋势预测。该平台的人工智能趋势预测引擎依靠历史价格数据来预测不断变化的市场趋势，它包括一个置信水平，因此您可以看到每个预测趋势的成功几率。 ",
      href: "https://tool.aiofchina.com/sites/494.html",
      url: "https://tickeron.com/",
    },
    {
      title: "Stock Hero",
      desc: " Stock Hero是一个多方面的平台，提供模拟现金交易，使您能够以无风险的方式测试您的策略。一旦您对结果感到满意，您就可以轻松地将您的机器人部署到现实世界中。",
      href: "https://tool.aiofchina.com/sites/490.html",
      url: "https://app.stockhero.ai/signup",
    },
    {
      title: "Sage AP",
      desc: "Sage AP Automation 对于那些与自由职业者和外部承包商一起工作的人很有用。人工智能业务工具自动记录支出和收入，同时还执行银行对账。它使用户能够将时间花在其他任务上，而不是手动输入数据。",
      href: "https://tool.aiofchina.com/sites/486.html",
      url: "https://www.quadient.com/en/ap-automation/integrations/sage-ap-automation",
    },
  ],
  AI设计: [
    {
      title: "ReRoom AI",
      desc: "室内设计AI 渲染工具，上传房间照片/设计草稿，探索各种设计风格（20+）, 今天就重新装修您的空间！",
      href: "https://tool.aiofchina.com/sites/688.html",
      url: "https://zh.reroom.ai/",
    },
    {
      title: "Magician",
      desc: "由 AI 提供支持的 Figma 神奇设计工具。",
      href: "https://tool.aiofchina.com/sites/192.html",
      url: "https://magician.design/",
    },
    {
      title: "Hotpot",
      desc: "用于创建图形、图片和文本的 AI 工具。",
      href: "https://tool.aiofchina.com/sites/191.html",
      url: "https://hotpot.ai/",
    },
    {
      title: "MakeLogoAI",
      desc: "生成独特的徽标",
      href: "https://tool.aiofchina.com/sites/190.html",
      url: "https://makelogo.ai/",
    },
    {
      title: "Pebblely",
      desc: "在几秒钟内为任何产品创建漂亮的照片。",
      href: "https://tool.aiofchina.com/sites/189.html",
      url: "https://pebblely.com/",
    },
    {
      title: "[可试用]Flair",
      desc: "使用您自己的品牌对象生成产品照片。",
      href: "https://tool.aiofchina.com/sites/188.html",
      url: "https://allthingsai.com/",
    },
    {
      title: "IconifyAI",
      desc: "AI 工具，让您在几秒钟内为您的应用程序/网站创建专业图标。",
      href: "https://tool.aiofchina.com/sites/187.html",
      url: "https://www.iconifyai.com/",
    },
    {
      title: "Clickable",
      desc: "适用于所有营销渠道的精美、品牌一致且转化率高的广告。",
      href: "https://tool.aiofchina.com/sites/186.html",
      url: "https://www.clickable.so/",
    },
    {
      title: "Galileo AI",
      desc: "Galileo AI 从简单的文本描述创建令人愉悦的、可编辑的 UI 设计。",
      href: "https://tool.aiofchina.com/sites/185.html",
      url: "https://www.usegalileo.ai/",
    },
    {
      title: "Contentinator",
      desc: "轻松为您的 Figma 设计生成逼真的内容。",
      href: "https://tool.aiofchina.com/sites/184.html",
      url: "https://contentinator.com",
    },
  ],
  自动化: [
    {
      title: "AI DRIVE",
      desc: "下一代 AI驾驶技术解决方案旨在提高驾驶员安全性、实现环境监控并增强车辆可用性。",
      href: "https://tool.aiofchina.com/sites/551.html",
      url: "https://ai-drive.com",
    },
    {
      title: "Bardeen",
      desc: "直接从浏览器自动执行重复性任务，无需代码。",
      href: "https://tool.aiofchina.com/sites/199.html",
      url: "https://www.bardeen.ai/",
    },
    {
      title: "Levity",
      desc: "更快地浏览文本、文档和图像。 没有一行代码。",
      href: "https://tool.aiofchina.com/sites/198.html",
      url: "https://levity.ai/",
    },
    {
      title: "Automagicals",
      desc: "编写有关如何构建自动化的详细文档的 AI。",
      href: "https://tool.aiofchina.com/sites/197.html",
      url: "https://www.automagicals.com/",
    },
  ],
  学习辅助: [
    {
      title: "Tutor AI",
      desc: "AI助教教你学习任何知识",
      href: "https://tool.aiofchina.com/sites/549.html",
      url: "https://www.tutorai.me",
    },
    {
      title: "[开源]ChatGPT Prompts",
      desc: "此 repo 包括 ChatGPT promt 管理以更好地使用 ChatGPT。",
      href: "https://tool.aiofchina.com/sites/204.html",
      url: "https://github.com/f/awesome-chatgpt-prompts",
    },
    {
      title: "Prompt Hunt",
      desc: "Prompt Hunt 使创建、编辑和共享样式和主题变得容易。",
      href: "https://tool.aiofchina.com/sites/203.html",
      url: "https://www.prompthunt.com/",
    },
    {
      title: "[开源]PromptLayer",
      desc: "记录、跟踪和调试您的提示和 OpenAI API 请求。",
      href: "https://tool.aiofchina.com/sites/202.html",
      url: "https://promptlayer.com/",
    },
    {
      title: "Promptbase",
      desc: "查找最佳提示，产生更好的结果，节省 API 成本，销售您自己的提示。",
      href: "https://tool.aiofchina.com/sites/201.html",
      url: "https://promptbase.com/",
    },
    {
      title: "[完全免费]Learn Prompting",
      desc: "关于与人工智能通信的免费开源课程。",
      href: "https://tool.aiofchina.com/sites/200.html",
      url: "https://learnprompting.org/",
    },
  ],
  阅读: [
    {
      title: "Azure 沉浸式阅读器",
      desc: "使用 Azure 沉浸式阅读器（一种 Azure 应用 AI 服务）将文本阅读和理解功能嵌入应用程序。它基于 Azure 认知服务构建，可加速实现由 AI 驱动的解决方案，该解决方案可通过各种阅读器工具和功能（如大声阅读、翻译语言，以及通过突出显示和其他设计元素吸引注意力）来帮助所有年龄和阅读能力的用户。Azure 是唯一提供此类文本阅读技术的主要云提供商。无需机器学习专业知识即可使用。",
      href: "https://tool.aiofchina.com/sites/653.html",
      url: "https://azure.microsoft.com/zh-cn/products/immersive-reader",
    },
    {
      title: "Bearly",
      desc: "使用世界上最好的 AI 节省数百小时的阅读和写作时间。",
      href: "https://tool.aiofchina.com/sites/217.html",
      url: "https://bearly.ai/",
    },
    {
      title: "[完全免费]Konjer",
      desc: "Konjer 是一个满是名著的图书馆，您可以与之交谈。",
      href: "https://tool.aiofchina.com/sites/208.html",
      url: "https://www.konjer.xyz/",
    },
  ],
  数学: [
    {
      title: "AI:R MATH",
      desc: "数学人工智能已准备好回答您的问题。",
      href: "https://tool.aiofchina.com/sites/547.html",
      url: "https://www.airmath.com",
    },
  ],
  化学: [
    {
      title: "chemintelligence",
      desc: "无论您是开发配方、材料还是分子，我们的软件都可以加速您的研发。",
      href: "https://tool.aiofchina.com/sites/543.html",
      url: "https://chemintelligence.com/ai-for-chemistry",
    },
  ],
  生物学: [
    {
      title: "Cradle",
      desc: "Cradle 帮助生物学家使用 AI 设计建议设计改进的蛋白质。",
      href: "https://tool.aiofchina.com/sites/207.html",
      url: "https://cradle.bio/",
    },
    {
      title: "[公益]Valence AI",
      desc: "复杂生物学的新化学",
      href: "https://tool.aiofchina.com/sites/206.html",
      url: "https://www.valencediscovery.com/",
    },
    {
      title: "[公益]Exscientia",
      desc: "以患者为优先的 AI 可以更快地发现更好的药物",
      href: "https://tool.aiofchina.com/sites/205.html",
      url: "https://www.exscientia.ai/",
    },
  ],
  数据分析: [
    {
      title: "Viable",
      desc: "在不影响质量的情况下自动进行定性数据分析。",
      href: "https://tool.aiofchina.com/sites/215.html",
      url: "https://www.askviable.com/",
    },
    {
      title: "Synthetic Users",
      desc: "与 AI 参与者一起测试您的想法或产品，并自信地做出决定。",
      href: "https://tool.aiofchina.com/sites/211.html",
      url: "https://www.syntheticusers.com/",
    },
  ],
  论文工具: [
    {
      title: "人工智能内容检测器",
      desc: "将您的内容粘贴到下方，我们会告诉您是否有任何内容是在几秒钟内以异常准确的方式由 AI 生成的。",
      href: "https://tool.aiofchina.com/sites/532.html",
      url: "https://copyleaks.com/zh/features/ai-content-detector",
    },
    {
      title: "Papercrazy",
      desc: "全网最智能AI自动降重 帮助每位同学顺利通过查重关卡",
      href: "https://tool.aiofchina.com/sites/530.html",
      url: "https://www.papercrazy.cn/zhinengjiangchong.htm",
    },
    {
      title: "Elicit",
      desc: "Elicit 让您提出问题并从 1.75 亿篇研究论文中获得答案。",
      href: "https://tool.aiofchina.com/sites/218.html",
      url: "https://elicit.org/",
    },
    {
      title: "Explainpaper",
      desc: "上传一篇论文，突出令人困惑的文本，获得解释。",
      href: "https://tool.aiofchina.com/sites/216.html",
      url: "https://www.explainpaper.com/",
    },
    {
      title: "Lateral",
      desc: "一个网络应用程序，可帮助您在一个地方阅读、查找、共享和组织您的研究。 因此，您最多可以将其完成速度提高 10 倍。",
      href: "https://tool.aiofchina.com/sites/214.html",
      url: "https://www.lateral.io/",
    },
    {
      title: "[开源]Techcrunch Summarizer",
      desc: "复制并粘贴任何 TechCrunch 文章链接并自动对其进行总结。",
      href: "https://tool.aiofchina.com/sites/212.html",
      url: "https://allthingsai.com/tool/techcrunch-summarizer",
    },
  ],
  产品自动生成: [
    {
      title: "Jasper",
      desc: "Jasper 是面向企业的生成式 AI 平台，可帮助您的团队随时随地以 10 倍的速度为您的品牌量身定制内容。",
      href: "https://tool.aiofchina.com/sites/595.html",
      url: "https://www.jasper.ai/",
    },
    {
      title: "AdCreative",
      desc: "使用 AI 生成以转化为重点的广告创意和社交媒体帖子。",
      href: "https://tool.aiofchina.com/sites/222.html",
      url: "https://www.adcreative.ai/",
    },
    {
      title: "Peppertype",
      desc: "AI 内容编写工具，可在几秒钟内创建高转换内容。",
      href: "https://tool.aiofchina.com/sites/221.html",
      url: "https://www.peppertype.ai/",
    },
    {
      title: "Ocoya",
      desc: "一个使用 AI 更快地创建、自动生成和安排内容的平台。",
      href: "https://tool.aiofchina.com/sites/220.html",
      url: "https://www.ocoya.com/",
    },
  ],
  AI玄学: [
    {
      title: "寻艾中医AI开放平台",
      desc: "AI中医智能",
      href: "https://tool.aiofchina.com/sites/575.html",
      url: "https://www.xun-ai.cn/home",
    },
    {
      title: "Lunar",
      desc: "lunar是一个支持阳历、阴历、佛历和道历的日历工具库，它开源免费，有多种开发语言的版本，不依赖第三方，支持阳历、阴历、佛历、道历、儒略日的相互转换，它能用来制作日历，甚至算命。  除此之外，还支持星座、干支、生肖、节气、节日、彭祖百忌、每日宜忌、吉神宜趋、凶煞宜忌、吉神方位、冲煞、纳音、星宿、八字、五行、十神、建除十二值星、青龙名堂等十二神、黄道日及吉凶等。",
      href: "https://tool.aiofchina.com/sites/538.html",
      url: "https://6tail.cn/calendar/api.html#overview.html",
    },
    {
      title: "Tarot Moon",
      desc: "AI巫婆在线塔罗牌算命",
      href: "https://tool.aiofchina.com/sites/536.html",
      url: "https://tarotmoon.com",
    },
  ],
};
