import type { Metadata } from "next";
import { Inter } from "next/font/google";
import LenisProvider from "@/components/Providers/LenisProvider";
import "./ui/globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <LenisProvider>
        <body className={inter.className} style={}>
          {children}
        </body>
      </LenisProvider>
    </html>
  );
}
